# Generated by Django 3.1.4 on 2020-12-16 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutuser', '0002_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutuser',
            name='follow',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
